# docker-compose up -d
services:
  db:
    image: postgres:17.4-alpine3.21
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: "PFT_DB"
      POSTGRES_USER: "pft_admin"
      POSTGRES_PASSWORD: "pft_password"
    ports:
      - "5432:5432"

  adminer:
    depends_on:
      - db
    image: adminer:5.1.0
    restart: always
    ports:
      - "8088:8080"